### ISSUE TITLE
warning: could not load encoding for file.encoding of MS932 in jruby

### ISSUE THREAD

**Issue by yamam** [jruby/jcodings#16]
In Windows 7 , jruby 9.1.2.0, following warning occours.

```
jruby -we ''
C:/jruby-9.1.2.0/lib/ruby/stdlib/rubygems.rb:117: warning: could not load encoding for file.encoding of MS932, using default external
```

In my environment, file.encoding is MS932. But in EncodingList.java there isn't MS932.
So, please add the follwing entry.

```
EncodingDB.alias("MS932", "Windows-31J");
```

**Comment by lopex** [comment]
MS932 seems to only appear in nkf ext in mri.

**Comment by yamam** [comment]
MS932 is equivalent to Windows-31J in java.
Please refer to the following site.
https://docs.oracle.com/javase/7/docs/technotes/guides/intl/encoding.doc.html
```
windows-31j MS932 Windows Japanese
```

**Comment by lopex** [comment]
Fixed in https://github.com/jruby/jcodings/commit/d70bea3b9551283a66019035f4abd6a482de01fe
