### ISSUE TITLE
Verify org.jruby.jcodings:jcodings:1.0.44 is JDK11 compatible

### ISSUE THREAD

**Issue by AlexeyRedinskii** [jruby/jcodings#27]
Hello guys,

we are in the process of migrating from JDK8 to JDK11. Our internal tool says that org.jruby.jcodings:jcodings:1.0.44 is not not JDK11 compatible, because it uses covariant methods:

> This project contains references to covariant Java API methods that are not provided in JDK 8.
> 
> Incompatible bytecode compiled with JDK 9+ may throw a java.lang.NoSuchMethodError when running on JDK 8. An example are implementations of java.nio.Buffer.
> 
> Ensure that bytecode compiled to run on JDK 8 uses the -release 8 option. Bytecode built using compiler options -source 1.8 and -target 1.8 do not ensure compatible bytecode.
> 
> NoSuchMethodError exceptions may also be mitigated by up casting types such as: ((Buffer) charBuffer).flip()

Could you please verify/release a new version that is JDK11 compatible?

**Comment by AlexeyRedinskii** [comment]
@lopex @headius please ^

**Comment by lopex** [comment]
Does maven-release-plugin have an option for -release 8 ?

**Comment by ahorek** [comment]
@lopex yes
https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html

there's also a way how to fix it without setting compatibility flags, see https://github.com/headius/backport9

but I don't think it's necessary, jcodings doesn't use methods such as ((Buffer) CharBuffer).flip()
it should be fine

**Comment by headius** [comment]
I actually fixed this for my GraalVM experiments. Pushing release now. Sorry for delay!

**Comment by headius** [comment]
BTW, what tool is that?

**Comment by headius** [comment]
Release 1.0.45 should be out there now!
