### ISSUE TITLE
jcodings does not properly produce error for at least two encodings on bad codepoint

### ISSUE THREAD

**Issue by headius** [jruby/jcodings#7]
Originally reported as http://jira.codehaus.org/browse/JRUBY-5228

Two expectations fail from this...the latter two in the following spec from Integer#chr specs:

``` ruby
    it "raises a RangeError if self is an invalid codepoint for the given encoding" do
      lambda { 0x81.chr(Encoding::EUC_JP)     }.should raise_error(RangeError)
      lambda { 256.chr(Encoding::ISO_8859_9)  }.should raise_error(RangeError)
      lambda { 620.chr(Encoding::TIS_620)     }.should raise_error(RangeError)
    end
```

The EUC_JP line properly produces an EncodingException inside jcodings, but the other two do not.

**Comment by lopex** [comment]
@headius all of those seem to be raising now
